/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.InventarioConrtoller;
import controllers.ProductController;
import controllers.SupplierController;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import lib.utils.DateTimeUtility;
import lib.utils.ErrorHandler;
import models.Inventory;
import models.Product;
import models.Supplier;
import models.User;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author luis
 */
public class GestionView extends javax.swing.JFrame {
    DefaultTableModel tableProductModel;

    String[] header = {"id", "name"};
    String[][] data;

    User user;
    ArrayList<Supplier> supplierList;
    
    
    ProductController productController;
    InventarioConrtoller inventoryController;
    SupplierController supplierController;
   
    public GestionView() throws Exception{
        initComponents();
        
        this.user = user;

        productController = new ProductController();
        inventoryController = new InventarioConrtoller();
        supplierController = new SupplierController();

        createProductTable();
        initProductTable();

        
        /*ADD PRODUCTS
        
        Supplier supplier1 = new Supplier();
        supplier1.setId(1);
        supplier1.setName("Supplier 1");

        Supplier supplier2 = new Supplier();
        supplier2.setId(2);
        supplier2.setName("Supplier 2");

        supplierList.add(supplier1);
        supplierList.add(supplier2);
        
        Product product1 = new Product();
        product1.setId(1);
        product1.setName("Product 1");
        product1.setStock(10);
        product1.setDate(LocalDate.now());
        product1.setSupplier(supplier1); 

        Product product2 = new Product();
        product2.setId(2);
        product2.setName("Product 2");
        product2.setStock(20);
        product2.setDate(LocalDate.now().minusDays(1));
        product2.setSupplier(supplier2); 

        Product product3 = new Product();
        product3.setId(3);
        product3.setName("Product 3");
        product3.setStock(15);
        product3.setDate(LocalDate.now().minusDays(2)); 
        product3.setSupplier(supplier1); 

        Product product4 = new Product();
        product4.setId(4);
        product4.setName("Product 4");
        product4.setStock(8);
        product4.setDate(LocalDate.now().minusDays(3)); 
        product4.setSupplier(supplier2); 

        Product product5 = new Product();
        product5.setId(5);
        product5.setName("Product 5");
        product5.setStock(25);
        product5.setDate(LocalDate.now().minusDays(4)); 
        product5.setSupplier(supplier1); 

        products.add(product1);
        products.add(product2);
        products.add(product3);
        products.add(product4);
        products.add(product5);
        
        //END */
        loadSupplier();
       
        loadProductTable(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        labelStock = new javax.swing.JLabel();
        CBSupplier = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        txtID = new javax.swing.JTextField();
        labelNombre1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        jLabel1.setText("GESTIÓN DE DISPOSITIVOS");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 15ButtonSave.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        labelNombre.setText("NOMBRE");

        jLabel4.setText("PROVEEDOR");

        jLabel11.setText("FECHA DE ADQUISICIÓN");

        labelStock.setText("STOCK");

        CBSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSupplierActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Frame 22ButtonUpdate.png"))); // NOI18N

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableProduct);

        labelNombre1.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(labelNombre1)
                            .addGap(355, 355, 355)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(labelNombre)
                            .addGap(314, 314, 314)
                            .addComponent(labelStock))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(CBSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(42, 42, 42)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelNombre1)
                        .addComponent(jLabel11))
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(7, 7, 7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelNombre)
                        .addComponent(labelStock))
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(1, 1, 1)
                            .addComponent(CBSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
         Inventory inventory = new Inventory();
        Supplier supplier = null;


     
        Product product = new Product();
        product.setId(Integer.parseInt(txtID.getText()));
        product.setName(txtNombre.getText());
        product.setStock(Integer.parseInt(txtStock.getText()));
        product.setSupplier(supplier);
        
        DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        product.setDate(LocalDate.parse(txtFecha.getText(), format));
        
        try {
            productController.saveProduct(product);
        } catch (SQLException ex) {
            Logger.getLogger(GestionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel5MousePressed

    private void CBSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSupplierActionPerformed
        // TODO add your handling code here:
        String supplierSelected = CBSupplier.getSelectedItem().toString();
        try {
            loadProductTable(searchSupplierId(supplierSelected));
        } catch (Exception ex) {
            Logger.getLogger(GestionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CBSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestionView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(GestionView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private int searchSupplierId(String name) {
        for (Supplier supplier : supplierList) {
            if (supplier.getName().toLowerCase().contains(name.toLowerCase())) {
                return supplier.getId();
            }
        }
        return 0;
    }
    public void details(boolean enableEdit) {
        CBSupplier.setEnabled(enableEdit);
    }

    public void setDataField(Product product) {
        txtID.setText(String.valueOf(product.getId()));
        txtNombre.setText(product.getName());
        txtStock.setText(String.valueOf(product.getStock()));
        txtFecha.setText(String.valueOf(product.getDate()));
        CBSupplier.addItem(product.getSupplier().getName());
    }
    private Object[] getDataProductField() {
        Object[] data = {
            txtID.getText(),
            txtNombre.getText(),
            txtStock.getText(),
        };
        return data;
    }
            
    
    private void initProductTable() {
        tableProduct.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tableProduct.getSelectedRows();
//        tableProduct.setSelectionMode(new ListSelectionListener() {
//            public void valueChance
//        });
    }

    private void createProductTable() {
        tableProductModel = new DefaultTableModel(data, header);
        tableProduct.setModel(tableProductModel);
    }

    private void loadProductTable(int id) throws Exception {
        ArrayList<Product> productList = productController.getProducts();
        tableProductModel.setNumRows(0);
        for (Product product : productList) {
            if (id == product.getSupplier().getId()) {
                Object[] row = {product.getId(), product.getName()};
                tableProductModel.addRow(row);
            } 
        }
    }

    private ArrayList<Product> getSelectedProducts() {
        ArrayList<Product> productList = new ArrayList<>();
        Product product;

        for (int row : tableProduct.getSelectedRows()) {
            Object value = tableProduct.getValueAt(row, 0);
            product = new Product();
            product.setId(Integer.parseInt((String.valueOf(value))));
            productList.add(product);
        }

        return productList;
    }

    private Supplier getSelectedSupplier() {
        String supplierName = String.valueOf(CBSupplier.getSelectedItem());
        for (Supplier supplier : supplierList) {
            if (supplier.getName().equalsIgnoreCase(supplierName)) {
                return supplier;
            }
        }

        return null;
    }

    private void loadSupplier() throws Exception {
        //supplierList = supplierController.getSuppliers();

        for (Supplier supplier : supplierList) {
            CBSupplier.addItem(supplier.getName());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelStock;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
